# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = '47991657611ddfca9e6c25ea83a385bc'
  config.secret_key = ''
  config.default_from = ''
  config.api_version = 'v3.1'
end
